# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: jhi-mf-blog
services:
  consul:
    image: docker.io/hashicorp/consul:1.22.3
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8300:8300
      - 127.0.0.1:8500:8500
      - 127.0.0.1:8600:8600
    command: consul agent -dev -ui -client 0.0.0.0 -log-level=INFO
    labels:
      org.springframework.boot.ignore: true
