apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: demo
#common configuration shared between all applications
data:
  application.yml: |-
    configserver:
      name: Consul
      status: Connected to Consul running in Kubernetes
    jhipster:
      security:
        authentication:
          jwt:
            base64-secret: Mzg5ODIwZGRlOGIyMDg5NmYxM2UxMjJkN2UyMzljMzM0YWRjOTIwNzExMmM0ZjNlNGY3MGNjNmRiNDZiYzI3NGZhMmVlZGFlM2FmYzUyMzFlM2EzOWExYmU5OTZjOWU4ODlmNg==
  # app specific configuration
