apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: chessequality/gateway
      context: ../gateway
      jib: {}
    - image: chessequality/blog
      context: ../blog
      jib: {}
    - image: chessequality/store
      context: ../store
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
